[project]
name = "quarto-collapse-output"
version = "0.1.0"
requires-python = ">=3.13"
dependencies = [
    "jupyter>=1.1.1",
    "matplotlib>=3.10.7",
    "papermill>=2.6.0",
    "plotnine>=0.15.0",
    "polars>=1.34.0",
    "pyarrow>=21.0.0",
]
